# Generated by Django 3.2.9 on 2023-04-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_restaurants_business_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='business_hours',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='friday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='monday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='saturday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='sunday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='thursday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='tuesday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='wednesday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
