# Generated by Django 3.2.9 on 2023-04-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20230410_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_score',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
