# Generated by Django 4.1.6 on 2023-02-21 09:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_tag_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=300)),
                ('table', models.PositiveSmallIntegerField()),
                ('Genre', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
