# Generated by Django 4.1.7 on 2023-03-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_review_created_at_review_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
    ]
