# Generated by Django 4.1.6 on 2023-03-26 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_rename_user_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('num_people', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.restaurants')),
            ],
        ),
    ]
