# Generated by Django 4.1.6 on 2023-03-31 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
    ]
