# Generated by Django 4.1.6 on 2023-03-31 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_reservation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
